name: physikell
version: 0.1.0.0
dependencies:
  - base
  - ad
  - pretty-simple
  - physics
library:
  source-dirs: .
  exposed-modules:
    - Schrodinger
  other-modules: []
  default-extensions:
    - ConstraintKinds
    - RankNTypes
    - TypeOperators
    - UnicodeSyntax
    - ViewPatterns
