cabal-version: 1.12

name:           standard-model
version:        0.1.0.0
build-type:     Custom

custom-setup
  setup-depends:
      base
    , Cabal
    , graphmod
    , graphviz
    , silently
    , text
    , haskell-src-exts

library
  exposed-modules:
      Algebra.GradedRing
      Physics.DimensionalAnalysis
      Physics.Quantum.Dirac
      Physics.Quantum.Mechanics
  default-extensions:
      BlockArguments
      ConstraintKinds
      DataKinds
      FlexibleInstances
      FunctionalDependencies
      MultiParamTypeClasses
      PostfixOperators
      Rank2Types
      RebindableSyntax
      ScopedTypeVariables
      TypeApplications
      TypeOperators
      UnicodeSyntax
      ViewPatterns
  build-depends:
      ad
    , base
    , dimensional
    , hmatrix
    , numtype-dk
    , numeric-prelude
    , physics
    , plotlyhs
    , pretty-simple
  default-language: Haskell2010
